content/urls.py
from django.urls import path
from content import views

# TEMPLATE TAGGING
app_name = "content"

urlpatterns = [
    # path("", views.index, name="index"),
    path("register/", views.register, name="register"),
    path("user_login/", views.user_login, name="user_login"),
]

dj_lvl5/urls.py
from django.contrib import admin
from django.urls import path, include  # add this line
from content import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("content/", include("content.urls")),
    path("logout/", views.user_logout, name="logout"),
    path("special/", views.special, name="special"),
]

content/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


# UserProfileInfo model
class UserProfileInfo(models.Model):
    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to="profile_pics", blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

content/forms.py
from django import forms
from django.contrib.auth.models import User
from content.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "email", "password")


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ("portfolio_site", "profile_pic")

content/views.py
from django.shortcuts import render
from content.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.


def index(request):
    # context_dict = {"text": "hello world", "number": 100}
    return render(request, "content/index.html")


def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            # check if they provided a profile picture
            if "profile_pic" in request.FILES:
                profile.profile_pic = request.FILES["profile_pic"]

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(
        request,
        "content/registeration.html",
        {
            "user_form": user_form,
            "profile_form": profile_form,
            "registered": registered,
        },
    )


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("Account not active")
        else:
            print("login failed")
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, "content/login.html")

templates/content/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div>
      <a href="{% url 'index' %}">Home</a>
      <a href="{% url 'admin:index' %}">Admin</a>
      <a href="{% url 'content:register' %}">Register</a>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
      {% else %}
        <a href="{% url 'content:user_login' %}">Login</a>
      {% endif %}
    </div>

    {% block body_block %}

    {% endblock %}
  </body>
</html>

templates/content/index.html
{% extends 'content/base.html' %}
{% block body_block %}
  <h1>Index html page</h1>
{% endblock %}

templates/content/login.html
{% extends 'content/base.html' %}
{% block body_block %}
  <h1>please login</h1>
  <form action="{% url 'content:user_login' %}" method="POST">
    {% csrf_token %}username<input type="text" name="username" /><br />
    password<input type="password" name="password" />
    <input type="submit" value="login" />
  </form>
{% endblock %}

templates/content/registeration.html
{% extends 'content/base.html' %}
{% load static %}
{% block body_block %}
  {% if registered %}
    <h1>Thank you for registring</h1>
  {% else %}
    <h1>Register here</h1>
    <h3>Fill the form</h3>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      <hr>
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register" />
    </form>
  {% endif %}
{% endblock %}